version: '3.7'
services:
  merlin:
    build:
      context: .
    image: merlin
    container_name: merlin
    network_mode: host
    environment:
      - DISPLAY
    user: ${CURRENT_UID} # https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15
    ports:
      - '8081:8081'
    #command: 'yarn dev'
    volumes:
      - .:/app
      - /app/node_modules # prevents the container from polluting local directory
      - $HOME/.Xauthority:/root/.Xauthority:rw # Share X server with container https://medium.com/@SaravSun/running-gui-applications-inside-docker-containers-83d65c0db110
